### ISSUE TITLE
Fooocus can't see custom models

### ISSUE THREAD

**Issue by daudk3** [ashleykleynhans/fooocus-docker#5]
Hi, I added some custom checkpoints and loras to /workspace/Fooocus/models/checkpoints and /workspace/Fooocus/models/loras using Jupyter but when I click "Refresh All Files" in the web ui nothing happens. Only the default base model shows up.

**Comment by ashleykleynhans** [comment]
Don't use Jupyter to upload models, use runpodctl/croc/sftp etc, checkpoints not showing is a known bug in Jupiter and also I don't develop Jupyter so if you have issues with Jupyter log an issue in Jupyter Github repo.

**Comment by daudk3** [comment]
I don't understand why I would need croc/sftp to add a model when I'm running this completely locally (for now at least). Here is my docker-compose.yml:

```
version: "3.3"
services:
  fooocus:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    volumes:
      - ./workspace:/workspace
    ports:
      - 3000:3001
      - 8888:8888
    environment:
      - JUPYTER_PASSWORD=Jup1t3R!
    image: ashleykza/fooocus:latest
networks: {}
```

I'm struggling to understand what I'm doing wrong here. When I docker exec into the container and navigate to the workspace directory I can see the models I put there but Fooocus just can't see them no matter what. I'm sorry if this question is stupid, I'm still learning when it comes to Docker.
